# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- '*'
pool:
  vmImage: 'ubuntu-18.04'
  demands:
  - npm
variables:
  buildConfiguration: 'Release'
  Steps:
          - task: UseDotNet@2
            displayName: 'User .NET Core SDK 3.1.300'
            inputs:
                    PackageType: sdk
                    version: 3.1.300
