# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- '*'
pool:
  vmImage: 'ubuntu-18.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'
  
steps:
        - task: UseDotNet@2
          displayName: 'Use'
          inputs:
                  packageType: sdk
                  version: 3.1.300
        - task: Npm@1
            displayName: 'Run npm install'
            inputs:
                    verbose: false
